version: "3"
services:
 # react app container service
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  
  # node-express container service
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  
  # mongodb container service
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db

# explicitly defining the networks for containers
networks:
  mern-app:
    driver: bridge

volumes:
  mongo-data:
    driver: local